Sem 7/Distributed System/Mini Project V3/DistributedFileSharing/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    re_path(r'^file/', include('filesharing.urls'))
]

Sem 7/Distributed System/Mini Project V3/filesharing/urls.py
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView
from . import views

app_name='filesharing'

urlpatterns = [
    # Home page URL
    re_path(r'^$',views.file_home, name='file_home'),

    # Download URLs
    re_path(r'^download/$', views.download_home, name='download'),
    re_path(r'^download/music/$', views.download_music,name='download_music'),
    re_path(r'^download/photos/$', views.download_photos, name='download_photos'),

    # Upload URLs
    re_path(r'^upload/$', views.upload_home, name='upload'),
    re_path(r'^upload/music/$', views.upload_music, name='upload_music'),
    re_path(r'^upload/photos/$', views.upload_photos, name='upload_photos'),

]

Sem 7/Distributed System/Mini Project V3/filesharing/models.py
from django.db import models

# Create your models here.

Sem 7/Distributed System/Mini Project V3/filesharing/views.py
from django.shortcuts import render
import os
import socket

PORT = 1234
MAIN_SERVER_IP = '192.168.43.20'
FILEPATH = './Downloads/'
CONNECTED_TO_SERVER=False
client_socket=None

# Create your views here.
def file_home(request):
    global CONNECTED_TO_SERVER
    global client_socket

    if not CONNECTED_TO_SERVER:
        try:
            client_socket = socket.socket()
            client_socket.connect((MAIN_SERVER_IP, PORT))
            CONNECTED_TO_SERVER=True
        except:
            print('Main Server Down ..')
            CONNECTED_TO_SERVER=False
            
    return render(request,'filesharing/file_home.html')

# Download Views
def download_home(request):
    if request.method == 'POST':
        return render(request,'filesharing/download_home.html')
    else:
        return render(request,'not_found.html')

def download_music(request):
    if request.method == 'POST':
        if request.POST.get("this_contains") == "Music":
            client_socket.send("2".encode())
            file_data = client_socket.recv(1024).decode()
            list_of_files = file_data.split('**')

            return render(request,'filesharing/download_music.html',{"list_of_file":list_of_files})
        elif request.POST.get("object_id"):
            # file_data=request.POST.get("file_data")
            # list_of_files = request.POST.get("list_of_file")
            filename=request.POST.get("object_id") #add up
            client_socket.send(filename.encode())
            if(filename == '0'):  
                return render(request, 'filesharing/download_home.html')
            
            file_pointer = open(FILEPATH + filename, 'wb')
            filedata = client_socket.recv(1024)
            print('Getting', filename, 'from server...')
            while filedata:
                file_pointer.write(filedata)
                filedata = client_socket.recv(1024)
                if filedata[-4:] == b'DONE':
                    filedata = None
                    break
            print('Got', filename, 'from server.')
            file_pointer.close()
            file_data = client_socket.recv(1024).decode()
            list_of_files = file_data.split('**')

            return render(request,'filesharing/download_music.html',{"list_of_file":list_of_files})

    return render(request,'not_found.html')

def download_photos(request):
    if request.method == 'POST':
        if request.POST.get("this_contains") == "Photo":
            client_socket.send("1".encode())
            file_data = client_socket.recv(1024).decode()
            list_of_files = file_data.split('**')

            return render(request,'filesharing/download_photos.html',{"list_of_file":list_of_files})
        elif request.POST.get("object_id"):
            # file_data=request.POST.get("file_data")
            # list_of_files = request.POST.get("list_of_file")
            filename=request.POST.get("object_id") #add up
            client_socket.send(filename.encode())
            if(filename == '0'):
                return render(request, 'filesharing/download_home.html')
            
            file_pointer = open(FILEPATH + filename, 'wb')
            filedata = client_socket.recv(1024)
            print('Getting', filename, 'from server...')
            while filedata:
                file_pointer.write(filedata)
                filedata = client_socket.recv(1024)
                if filedata[-4:] == b'DONE':
                    filedata = None
                    break
            print('Got', filename, 'from server.')
            file_pointer.close()
            file_data = client_socket.recv(1024).decode()
            list_of_files = file_data.split('**')
            
            return render(request,'filesharing/download_photos.html',{"list_of_file":list_of_files})
    return render(request,'not_found.html')


# Upload Views
def upload_home(request):
    return render(request,'filesharing/upload_home.html')
    # return render(request,'not_found.html')

def upload_music(request):
    # return render(request,'filesharing/upload_music.html')
    return render(request,'not_found.html')

def upload_photos(request):
    # return render(request,'filesharing/upload_photos.html')
    return render(request,'not_found.html')

Sem 7/Distributed System/Mini Project V3/filesharing/templates/filesharing/download_home.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/filesharing/style.css' %}">

        <title>Trans Media | Download</title>
    </head>
    <body>
      <header class="header-2">

        <div class="header__text-box">
          <h1 class="heading-primary-1">
            <span class="heading-primary--main">music and photos</span>
            <span class="heading-primary--sub">on the go</span>
          </h1>

        </div>

        <div class="header__btn-box-1">
          <form method="post" action="{% url 'filesharing:download_music' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn--brown btn--animated" name="this_contains" value="Music">Music</button>
            <!-- <a href="{% url 'filesharing:download_music' %}" class="btn btn--brown btn--animated">Music</a> -->
          </form>
        </div>

        <div class="header__btn-box-2">
          <form method="post" action="{% url 'filesharing:download_photos' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn--brown btn--animated" name="this_contains" value="Photo">Photos</button>
            <!-- <a href="{% url 'filesharing:download_photos' %}" class="btn btn--brown btn--animated">Photos</a> -->
          </form>
        </div>
      </header>
    </body>
</html>

Sem 7/Distributed System/Mini Project V3/filesharing/templates/filesharing/download_music.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/filesharing/style.css' %}">

        <title>Trans Media | Music</title>
    </head>
    <body>
      <header class="header-3">

        <div class="header__text-box header__util-1">
          <h1 class="heading-primary-1 heading-primary-util-1">
            <span class="heading-primary--main">contents</span>
          </h1>
        </div>

        <div class="list-box">
            {% for item in list_of_file %}
                <form class="list-item" method="post" action="{% url 'filesharing:download_music' %}">
                    {% csrf_token %}
                    <p class="list-element">{{ item }}</p>
                    <input type="hidden" name="list_of_file" value={{ list_of_file }} />
                    <button type="submit" class="btn--brown btn--animated btn-mini" name="object_id" value={{ item }}>Download</button>
                    <!-- <a href="#" class="btn--brown btn--animated btn-mini">Download</a> -->
                </form>
                <hr>
            {% endfor %}
            <form class="list-item" method="post" action="{% url 'filesharing:download_music' %}">
              {% csrf_token %}
              <p class="list-element">       </p>
              <input type="hidden" name="list_of_file" value={{ list_of_file }} />
              <button type="submit" class="btn--brown btn--animated btn-mini" name="object_id" value="0">Exit</button>
              <!-- <a href="#" class="btn--brown btn--animated btn-mini">Download</a> -->
            </form>
            <hr>
 
      </header>
    </body>
</html>

Sem 7/Distributed System/Mini Project V3/filesharing/templates/filesharing/download_photos.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/filesharing/style.css' %}">

        <title>Trans Media | Music</title>
    </head>
    <body>
      <header class="header-3">

        <div class="header__text-box header__util-1">
          <h1 class="heading-primary-1 heading-primary-util-1">
            <span class="heading-primary--main">contents</span>
          </h1>
        </div>

        <div class="list-box">
            {% for item in list_of_file %}
                <form class="list-item" method="post" action="{% url 'filesharing:download_photos' %}">
                    {% csrf_token %}
                    <p class="list-element">{{ item }}</p>
                    <input type="hidden" name="list_of_file" value={{ list_of_file }} />
                    <button type="submit" class="btn--brown btn--animated btn-mini" name="object_id" value={{ item }}>Download</button>
                    <!-- <a href="#" class="btn--brown btn--animated btn-mini">Download</a> -->
                </form>
                <hr>
            {% endfor %}
            <form class="list-item" method="post" action="{% url 'filesharing:download_photos' %}">
              {% csrf_token %}
              <p class="list-element">         </p>
              <input type="hidden" name="list_of_file" value={{ list_of_file }} />
              <button type="submit" class="btn--brown btn--animated btn-mini" name="object_id" value="0">Exit</button>
              <!-- <a href="#" class="btn--brown btn--animated btn-mini">Download</a> -->
            </form>
            <hr>
      </header>
    </body>
</html>

Sem 7/Distributed System/Mini Project V3/filesharing/templates/filesharing/file_home.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/filesharing/style.css' %}">

        <title>Trans Media | Home</title>
    </head>
    <body>
      <header class="header-1">

        <div class="header__text-box">
          <h1 class="heading-primary-1">
            <span class="heading-primary--main">transfer files</span>
            <span class="heading-primary--sub">at your fingertips</span>
          </h1>

        </div>

        <div class="header__btn-box-1">
          <form method="post" action="{% url 'filesharing:download' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn--brown btn--animated" value="Download">Download</button>
            <!-- <a href="" class="btn btn--brown btn--animated">Download</a> -->
          </form>
        </div>

        <div class="header__btn-box-2">
          <form method="post" action="{% url 'filesharing:upload' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn--brown btn--animated" value="Upload">Upload</button>
            <!-- <a href="{% url 'filesharing:upload' %}" class="btn btn--brown btn--animated">Upload</a> -->
          </form>
        </div>
      </header>
    </body>
</html>

Sem 7/Distributed System/Mini Project V3/filesharing/templates/filesharing/upload_home.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/filesharing/style.css' %}">

        <title>Trans Media | Upload</title>
    </head>
    <body>
      <header class="header-2">

        <div class="header__text-box">
          <h1 class="heading-primary-1">
            <span class="heading-primary--main">music and photos</span>
            <span class="heading-primary--sub">on the go</span>
          </h1>

        </div>

        <div class="header__btn-box-1">
          <form method="post" action="{% url 'filesharing:upload_music' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn--brown btn--animated" value="Music">Music</button>
            
          </form>
        </div>

        <div class="header__btn-box-2">
          <form method="post" action="{% url 'filesharing:upload_photos' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn--brown btn--animated" value="Photos">Photos</button>
            
          </form>
        </div>
      </header>
    </body>
</html>

Sem 7/Distributed System/Mini Project V3/filesharing/templates/filesharing/upload_music.html
<!DOCTYPE html>
<html>
    <title>Distributed File Sharing</title>
    <body>
        <h1>Music Upload</h1>
    </body>
</html>

Sem 7/Distributed System/Mini Project V3/filesharing/templates/filesharing/upload_photos.html
<!DOCTYPE html>
<html>
    <title>Distributed File Sharing</title>
    <body>
        <h1>Photos Upload</h1>
    </body>
</html>

Sem 7/Distributed System/Mini Project V3/filesharing/templates/home.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/filesharing/style.css' %}">

        <title>Trans Media</title>
    </head>
    <body>
      <header class="header">

        <div class="header__text-box">
          <h1 class="heading-primary">
            <span class="heading-primary--main">transmedia</span>
            <span class="heading-primary--sub">we transfer everything</span>
          </h1>

        </div>

        <div class="header__btn-box">
          <a href="{% url 'filesharing:file_home' %}" class="btn btn--brown btn--animated">Get Started</a>
        </div>
      </header>
    </body>
</html>

Sem 7/Distributed System/Mini Project V3/filesharing/templates/not_found.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Trans Media | 404</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:700,900" rel="stylesheet">

	<link rel="stylesheet" href="{% static '/css/not_found.css' %}">

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>404</h1>
				<h2>Page not found</h2>
			</div>
			<a href="{% url 'filesharing:file_home' %}">Homepage</a>
		</div>
	</div>

</body>

</html>